### ISSUE TITLE
Suggestion - Add the libheif binary files to the wheel when building

### ISSUE THREAD

**Issue by cdgriffith** [ram-nat/CyHeif#3]
Instead of having to specify them every package that uses it, include the `.dll` files in the wheel itself. 

For example just need to add the line: `data_files=[('bin', [str(x.absolute()) for x in pathlib.Path(lib_dirs[0]).glob("*.dll")])],` to the `setup(` section of `setup.py` 

Then in `cyheifloader\__init__.py` change the line to `libheif_path = os.getenv('LIBHEIF_PATH', os.path.join(sys.prefix, 'bin'))`

That way when you run `python setup.py bdist_wheel`, the wheel file itself could house the required files itself and be truly distributable. 
Currently untested on Linux, just Windows.

**Comment by ram-nat** [comment]
Great idea and thanks for the PR. Added a couple of comments to the PR.

**Comment by ram-nat** [comment]
Thanks again for adding the ability to package the dependencies on Windows.
